export default {
    NYLAS_CLIENT_ID: process.env.NYLAS_CLIENT_ID,
    NYLAS_API_KEY: process.env.NYLAS_API_KEY,
    API_ENDPOINT: process.env.API_ENDPOINT,
    NODE_ENV: process.env.NODE_ENV,
    BUBBLE_WEBHOOK_ENDPOINT: process.env.BUBBLE_WEBHOOK_ENDPOINT,
    BUBBLE_WEBHOOK_ENDPOINT_EVENTS: process.env.BUBBLE_WEBHOOK_ENDPOINT_EVENTS,
    BUBBLE_WEBHOOK_ENDPOINT_BOOKING: process.env.BUBBLE_WEBHOOK_ENDPOINT_BOOKING,
};
